name: Firmware build

on:
  push:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        board:
          - quakelight
          - frdm_mcxn947/mcxn947/cpu0
          - xiao_esp32c3
          - rpi_pico/rp2040/w

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@main
        with:
          app-path: firmware
          toolchains: arm-zephyr-eabi:riscv64-zephyr-elf
          ccache-cache-key: ${{ matrix.board }}

      - name: Fetch the blobs
        shell: python -u {0}
        run: |
          import os
          import sys

          module = ""
          if "${{ matrix.board }}" == "xiao_esp32c3":
            module="hal_espressif"
          elif "${{ matrix.board }}" == "rpi_pico/rp2040/w":
            module="hal_infineon"

          if not module:
            sys.exit(0)

          cmd = f"west blobs -a fetch {module}"

          for i in range(10):
            print(f"try {i}: {cmd}")
            if os.system(cmd) == 0:
              sys.exit(0)

          sys.exit(-1)

      - name: Build
        run: |
          echo west build -b ${{ matrix.board }} firmware -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y
          west build -b ${{ matrix.board }} firmware -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y
